  
version: '2'

services:
  orderer4.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.example.com
    networks:
      - outside
    volumes:
      - ./ordnode/byfn-sys-channel/byfn-sys-channel_last.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 10050:7050
networks:
  outside:
    external:
      name: net_byfn